export const newsList = [
  {
    title: "Tips Menjaga Kesehatan Ibu Hamil dan Janin dalam",
    text: "Kondisi tubuh seorang ibu sangat penting untuk dijaga, terutama pada masa kehamilan. Oleh sebab itu saya",
    link: "/",
    created: "2021-08-28T10:42:15Z",
    image: "/images/article1.png",
  },
  {
    title: "Tips Merawat Kesehatan Organ Intim Wanita",
    text: "Mulai dari berperan dalam menstruasi, seks, kehamilan, dan persalinan, vagina merupakan sa...",
    link: "/",
    created: "2021-07-23T10:42:15Z",
    image: "/images/article2.png",
  },
  {
    title: "Cara Mengetahui Siklus Haid Berjalan Normal ata...",
    text: "Siklus menstruasi merupakan serangkaian perubahan yang dialami tubuh wanita setiap bula...",
    link: "/",
    created: "2021-06-21T10:42:15Z",
    image: "/images/article3.png",
  },
  {
    title: "Apa Perbedaan USG 2D, 3D, dan 4D?",
    text: "Ibu yang sedang mengandung pasti ingin mengetahui perkembangan janin dari waktu k...",
    link: "/",
    created: "2021-06-18T10:42:15Z",
    image: "/images/article4.png",
  },
  {
    title: "Tips Merawat Kesehatan Organ Intim Wanita",
    text: "Mulai dari berperan dalam menstruasi, seks, kehamilan, dan persalinan, vagina merupakan sa...",
    link: "/",
    created: "2021-04-27T10:42:15Z",
    image: "/images/article2.png",
  },
  {
    title: "Tips Menjaga Kesehatan Ibu Hamil dan Janin dalam",
    text: "Kondisi tubuh seorang ibu sangat penting untuk dijaga, terutama pada masa kehamilan. Oleh sebab itu saya",
    link: "/",
    created: "2021-05-10T10:42:15Z",
    image: "/images/article1.png",
  },
  {
    title: "Cara Mengetahui Siklus Haid Berjalan Normal ata...",
    text: "Siklus menstruasi merupakan serangkaian perubahan yang dialami tubuh wanita setiap bula...",
    link: "/",
    created: "2021-05-21T10:42:15Z",
    image: "/images/article3.png",
  },
  {
    title: "Apa Perbedaan USG 2D, 3D, dan 4D?",
    text: "Ibu yang sedang mengandung pasti ingin mengetahui perkembangan janin dari waktu k...",
    link: "/",
    created: "2021-06-18T10:42:15Z",
    image: "/images/article4.png",
  },
  {
    title: "5 Hal yang Perlu Dilakukan dalam Mempersiapkan Pr...",
    text: "Memiliki buah hati tentu menjadi harapan bagi pasangan yang sudah menikah. Oleh sebab itu, b...",
    link: "/",
    created: "2021-04-27T10:42:15Z",
    image: "/images/article5.png",
  },
  {
    title: "6 Makanan Untuk Mendukung Program Keh...",
    text: "Agar program hamil berjalan lancar, setiap pasangan perlu mengonsumsi makanan yang ka...",
    link: "/",
    created: "2021-04-15T10:42:15Z",
    image: "/images/article6.png",
  },
  {
    title: "Yuk Kenalan Sama Program Bayi Tabung!",
    text: "Program bayi tabung adalah sebuah proses yang dilakukan melalui proses pembuahan sel te...",
    link: "/",
    created: "2021-04-03T10:42:15Z",
    image: "/images/article7.png",
  },
  {
    title: "Ingin Punya Bayi Kembar? Yuk, Cari Tau Program Ba...",
    text: "Setelah memasuki fase pernikahan dan menjalani hidup berumah tangga, tidak sedikit or...",
    link: "/",
    created: "2021-03-26T10:42:15Z",
    image: "/images/article8.png",
  },
  {
    title: "Kulit Bayi Mengelupas, Ketahui Cara Mengatasin...",
    text: "Kulit bayi mengelupas dapat terjadi di minggu-minggu awal kehidupannya setelah lahir. Hal in...",
    link: "/",
    created: "2021-03-12T10:42:15Z",
    image: "/images/article9.png",
  },
  {
    title: "Ketahui Kondisi Bayimu Melalui Warna Fesesnya",
    text: "Memperhatikan warna feses bayi diare dapat menjadi cara untuk mengetahui kondisi bayi. Berdas...",
    link: "/",
    created: "2021-02-07T10:42:15Z",
    image: "/images/article10.png",
  },
  {
    title: "4 Penyebab Diare pada Bayi dan Cara Mengatasi...",
    text: "Bayi dikatakan mengalami diare saat frekuensi buang air besarnya lebih dari 3 kali sehari dan kotora...",
    link: "/",
    created: "2021-01-21T10:42:15Z",
    image: "/images/article11.png",
  },
  {
    title: "Melatih Keterampilan Motorik Anak dengan Per...",
    text: "Keterampilan motorik adalah kemampuan untuk menggerakkan anggota tubuh, seperti kepala, bi...",
    link: "/",
    created: "2021-01-14T10:42:15Z",
    image: "/images/article12.png",
  },

  {
    title: "Melatih Keterampilan Motorik Anak dengan Per...",
    text: "Keterampilan motorik adalah kemampuan untuk menggerakkan anggota tubuh, seperti kepala, bi...",
    link: "/",
    created: "2021-01-14T10:42:15Z",
    image: "/images/article12.png",
  },
  {
    title: "4 Penyebab Diare pada Bayi dan Cara Mengatasi...",
    text: "Bayi dikatakan mengalami diare saat frekuensi buang air besarnya lebih dari 3 kali sehari dan kotora...",
    link: "/",
    created: "2021-01-21T10:42:15Z",
    image: "/images/article11.png",
  },
  {
    title: "Kulit Bayi Mengelupas, Ketahui Cara Mengatasin...",
    text: "Kulit bayi mengelupas dapat terjadi di minggu-minggu awal kehidupannya setelah lahir. Hal in...",
    link: "/",
    created: "2021-03-12T10:42:15Z",
    image: "/images/article9.png",
  },
];
