export const serviceList = [
  {
    title: "Polycystic Ovarian Syndrome (PCOS)",
    text: "Sindrom polikistik ovarium atau polycystic ovarian syndrome (PCOS) adalah gangguan hormon yang terjadi pada wanita di usia ...",
    link: "/",
    created: "2021-08-28T10:42:15Z",
    image: "/images/serviceImgs/service1.png",
  },
  {
    title: "Endometriosis",
    text: "Endometriosis adalah kondisi ketika endometrium tumbuh di luar dinding rahim. Pada kondisi ini, endometrium dapat bertumb...",
    link: "/",
    created: "2021-08-27T10:42:15Z",
    image: "/images/serviceImgs/service2.png",
  },
  {
    title: "Kista Endometriosis",
    text: "Kista endometriosis bisa dialami oleh remaja atau wanita dewasa. Kondisi ini paling sering menimbulkan gejala berupa kra...",
    link: "/",
    created: "2021-08-26T10:42:15Z",
    image: "/images/serviceImgs/service3.png",
  },
  {
    title: "Adenomiosis",
    text: "Adenomyosis atau adenomiosis adalah kondisi ketika endometrium atau lapisan permukaan rongga rahim tumbu...",
    link: "/",
    created: "2021-08-25T10:42:15Z",
    image: "/images/serviceImgs/service4.png",
  },
  {
    title: "Mioma",
    text: "Mioma merupakan suatu pertumbuhan daging di dalam rahim atau di luar rahim yang tidak bersifat ganas. Mioma bera...",
    link: "/",
    created: "2021-08-24T10:42:15Z",
    image: "/images/serviceImgs/service5.png",
  },
  {
    title: "Infeksi Ginekologi",
    text: "Peradangan di dalam alat kelamin pada wanita maupun pria merupakan masalah penting dalam ginekologi dan venereolo...",
    link: "/",
    created: "2021-08-23T10:42:15Z",
    image: "/images/serviceImgs/service6.png",
  },
  {
    title: "Polip Endometrium",
    text: "Polip endometrium juga dikenal sebagai polip rahim. Ini merupakan pertumbuhan jaringan yang tidak normal di lap...",
    link: "/",
    created: "2021-08-22T10:42:15Z",
    image: "/images/serviceImgs/service7.png",
  },
  {
    title: "Sumbatan Tuba Fallopi",
    text: "Tuba falopi merupakan bagian dari sistem reproduksi wanita yang berperan penting dalam proses menstruasi dan pembuah...",
    link: "/",
    created: "2021-08-21T10:42:15Z",
    image: "/images/serviceImgs/service8.png",
  },
  {
    title: "Evaluasi Awal Infertilitas Pria",
    text: "Gangguan kesuburan atau infertilitas pria merupakan salah satu faktor yang dapat menghambat pasangan untuk m...",
    link: "/",
    created: "2021-08-20T10:42:15Z",
    image: "/images/serviceImgs/service9.png",
  },
  {
    title: "Analisa Sperma",
    text: "Pemeriksaan sperma adalah prosedur yang dilakukan untuk menganalisis kuantitas dan kualitas sperma. Selain itu, pemer...",
    link: "/",
    created: "2021-08-19T10:42:15Z",
    image: "/images/serviceImgs/service10.png",
  },
  {
    title: "Gangguan Haid",
    text: "Gangguan menstruasi adalah kelainan yang terjadi pada siklus menstruasi. Ada beragam gangguan menstruasi yang dap...",
    link: "/",
    created: "2021-08-18T10:42:15Z",
    image: "/images/serviceImgs/service11.png",
  },
  {
    title: "Penjadwalan Laparoscopy",
    text: "Laparoskopi adalah prosedur yang dilakukan untuk memeriksa dan mengobati kondisi bagian dalam perut atau panggul. Prose...",
    link: "/",
    created: "2021-08-13T10:42:15Z",
    image: "/images/serviceImgs/service16.png",
  },
  {
    title: "Tracking Cycle",
    text: "Tracking cycle dalah pola perhitungan masa ovulasi atau masa subur, berdasarkan rata-rata siklus haid pada pasien wani...",
    link: "/",
    created: "2021-08-17T10:42:15Z",
    image: "/images/serviceImgs/service12.png",
  },
  {
    title: "IUI - Inseminasi",
    text: "Inseminasi buatan adalah salah satu prosedur medis untuk mengatasi masalah kesuburan (infertilitas). Inseminasi buatan b...",
    link: "/",
    created: "2021-08-16T10:42:15Z",
    image: "/images/serviceImgs/service13.png",
  },
  {
    title: "Program Bayi Tabung",
    text: "Bayi tabung adalah prosedur untuk membantu wanita agar bisa hamil. Prosedur ini diperuntukkan bagi pasangan yang sulit memili...",
    link: "/",
    created: "2021-08-15T10:42:15Z",
    image: "/images/serviceImgs/service14.png",
  },
  {
    title: "Histeroscopy",
    text: "Histeroskopi adalah prosedur pemeriksaan kondisi leher rahim dan bagian dalamnya. Prosedur ini dapat digunakan untuk mendi...",
    link: "/",
    created: "2021-08-14T10:42:15Z",
    image: "/images/serviceImgs/service15.png",
  },
  {
    title: "Polycystic Ovarian Syndrome (PCOS)",
    text: "Sindrom polikistik ovarium atau polycystic ovarian syndrome (PCOS) adalah gangguan hormon yang terjadi pada wanita di usia ...",
    link: "/",
    created: "2021-08-12T10:42:15Z",
    image: "/images/serviceImgs/service1.png",
  },
  {
    title: "Endometriosis",
    text: "Endometriosis adalah kondisi ketika endometrium tumbuh di luar dinding rahim. Pada kondisi ini, endometrium dapat bertumb...",
    link: "/",
    created: "2021-08-11T10:42:15Z",
    image: "/images/serviceImgs/service2.png",
  },
  {
    title: "Kista Endometriosis",
    text: "Kista endometriosis bisa dialami oleh remaja atau wanita dewasa. Kondisi ini paling sering menimbulkan gejala berupa kra...",
    link: "/",
    created: "2021-08-10T10:42:15Z",
    image: "/images/serviceImgs/service3.png",
  },
];
